logging:
  level:
    root: debug

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./local_database/database
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: secret
    lifeInMs: 3000000