spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never
app:
  jwt:
    secret: ${JWT_SECRET}
    lifeInMs: ${JWT_LIFE}
  employee:
    admin:
      login: ${ADMIN_LOGIN}
      password: ${ADMIN_PASSWORD}